### ISSUE TITLE
Post Belfast editorial changes

### ISSUE THREAD

**Issue by apolukhin** [ZaMaZaN4iK/numeric-papers-in-latex#10]
We need to:
* add constexpr (but not noexcept!)
* use spaceship operator
* replace macro with aliases
* fix typos

**Comment by ZaMaZaN4iK** [comment]
Should we try to redesign a little bit some classes (e.g. `unbounded_integer`)?

**Comment by apolukhin** [comment]
> Should we try to redesign a little bit some classes (e.g. `unbounded_integer`)?

Maybe. The redesign must be done via proposals with wording against P1889. Only editorial PR are allowed, not feature changing ones.
